# log frequency
val_check_interval: 20000.0
enable_progress_bar: true  # ✅ Changed from progress_bar_refresh_rate (deprecated after PL 1.5)

wandb:
  name: ${expname}
  group: ${expname}
  save_dir: ${workdir}
  project: mlcgmd
  entity: null
  log_model: true
  mode: online  # ✅ Removed quotes (YAML can parse it directly as string)

wandb_watch:
  log: all
  log_freq: 1000

lr_monitor:
  logging_interval: step
  log_momentum: false  # ✅ Removed semicolon and fixed to lowercase boolean
